name: Build and deploy

env:
  NODE_VERSION: '14'

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Pull and install
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: '195.2.92.114 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAxqO1p6Uv6BBKPkdqDFWcc+qLgHIrIkdvxBdcKufTaxJiUQ/KTas3OLZFpiVa006URirqta0WrCFe70xd1VTcY='

      - name: Trigger update via ssh
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '/root/ton_bot_update.sh'
